import { defineConfig } from 'tsup'

export default defineConfig([
  // 客户端安全入口
  {
    entry: ['src/client.ts', 'src/extension-client.ts'],
    format: ['cjs', 'esm'],
    dts: true,
    clean: false,
    splitting: false,
    sourcemap: true,
    treeshake: true,
    minify: false,
    target: 'esnext',
    outDir: 'dist',
    platform: 'browser',
    external: [
      'react',
      'react-dom',
      'next',
      // 排除所有Node.js模块，确保客户端构建纯净
      'fs',
      'fs/promises',
      'path',
      'os',
      'crypto',
      'stream',
      'util',
      'events',
      'child_process',
      'cluster',
      'v8',
      'chokidar',
      'fsevents',
      'commander',
      'yaml',
      'convict',
      'pino',
      'prom-client',
      'node:fs',
      'node:path',
      'node:crypto',
      'node:os',
      'node:url',
      'node:util',
      'node:stream',
      'node:events',
      'node:child_process',
      'node:cluster',
      'node:v8',
      '@opentelemetry/api',
      '@opentelemetry/exporter-jaeger',
      '@opentelemetry/exporter-prometheus',
      '@opentelemetry/instrumentation',
      '@opentelemetry/sdk-node',
      '@godaddy/terminus',
    ],
  },
  // Providers入口（客户端组件）
  {
    entry: ['src/providers.ts'],
    format: ['cjs', 'esm'],
    dts: true,
    clean: false,
    splitting: false,
    sourcemap: true,
    treeshake: true,
    minify: false,
    target: 'esnext',
    outDir: 'dist',
    platform: 'browser',
    external: [
      'react',
      'react-dom',
      'next',
      '@tanstack/react-query',
      'next-themes',
    ],
  },
  // 服务端入口
  {
    entry: ['src/index.ts', 'src/cli.ts', 'src/server.ts'],
    format: ['cjs', 'esm'],
    dts: true,
    clean: false,
    splitting: false,
    sourcemap: true,
    treeshake: true,
    minify: false,
    target: 'node18',
    outDir: 'dist',
    platform: 'node',
  external: [
    // Node.js built-in modules
    'fs',
    'fs/promises',
    'path',
    'os',
    'crypto',
    'stream',
    'stream/promises',
    'assert',
    'http',
    'https',
    'url',
    'zlib',
    'util',
    'events',
    'child_process',
    'cluster',
    'v8',
    // File system watching dependencies
    'chokidar',
    'fsevents',
    // CLI dependencies
    'commander',
    // Config and data parsing
    'yaml',
    'convict',
    // Observability dependencies
    'pino',
    'prom-client',
    '@opentelemetry/api',
    '@opentelemetry/exporter-jaeger',
    '@opentelemetry/exporter-prometheus',
    '@opentelemetry/instrumentation',
    '@opentelemetry/sdk-node',
    '@godaddy/terminus',
    // Other Node.js specific dependencies
    'node:fs',
    'node:path',
    'node:crypto',
    'node:os',
    'node:url',
    'node:util',
    'node:stream',
    'node:stream/promises',
    'node:events',
    'node:child_process',
    'node:cluster',
    'node:v8',
    // Next.js and React SSR dependencies
    'next',
    'next/dist/server',
    'next/dist/server/app-render',
    'next/dist/server/app-render/async-local-storage',
    'next/dist/server/app-render/action-async-storage-instance',
  ],
  },
])
